// Seeds the database from prisma/fixtures/*.json, generated by
// `bun run extract:frontend-data` from the actual live frontend content
// (see scripts/extract-frontend-data.mjs and docs/TRD.md §8).
//
// Run: bun run extract:frontend-data && bun run db:seed
//
// NOTE on images: the extraction script can only recover each image's
// *relative source path* (e.g. "src/assets/project-aurum-thumb.png"), not
// upload it anywhere — Vite resolves those imports to bundled URLs at build
// time, which a bare Node script has no equivalent for, and actually
// uploading to Cloudinary needs real API credentials this script doesn't
// assume are configured yet. This seed creates one `Asset` row per image
// pointing at that relative path as a placeholder `url`; before going live,
// either extend this script to actually upload each file via
// `src/services/storage.ts`'s `uploadToCloudinary`, or re-upload each one
// through the admin panel and repoint the affected Project/TeamMember rows.

import { PrismaClient } from "@prisma/client";
import { readFileSync, existsSync } from "node:fs";
import path from "node:path";
import { hashPassword } from "../src/utils/password";
import { PARTNERS } from "../src/services/validation";

const prisma = new PrismaClient();
const FIXTURES_DIR = path.resolve(__dirname, "fixtures");

function loadFixture<T>(name: string): T {
  const filePath = path.join(FIXTURES_DIR, name);
  if (!existsSync(filePath)) {
    throw new Error(
      `Missing prisma/fixtures/${name} — run "bun run extract:frontend-data" first.`,
    );
  }
  return JSON.parse(readFileSync(filePath, "utf8"));
}

function guessMimeType(filePath: string): string {
  const ext = path.extname(filePath).toLowerCase();
  return (
    { ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".webp": "image/webp", ".gif": "image/gif" }[
      ext
    ] ?? "application/octet-stream"
  );
}

async function upsertPlaceholderAsset(relativePath: string, altText: string, uploadedBy: string) {
  const existing = await prisma.asset.findFirst({ where: { url: relativePath } });
  if (existing) return existing;
  return prisma.asset.create({
    data: {
      url: relativePath,
      altText,
      mimeType: guessMimeType(relativePath),
      fileSize: 0,
      uploadedBy,
    },
  });
}

async function main() {
  console.log("Seeding database...");

  // ── Default admin user ────────────────────────────────────────────
  const seedAdminEmail = process.env.SEED_ADMIN_EMAIL ?? "nexorynofficial@gmail.com";
  const seedAdminPassword = process.env.SEED_ADMIN_PASSWORD ?? "change-me-immediately";
  // Naming it after one of the fixed Finance ledger actors (see
  // src/services/validation.ts's LEDGER_ACTORS) means the Finance page's
  // "your position" card resolves for this account out of the box.
  const seedAdminName = process.env.SEED_ADMIN_NAME ?? "Nexoryn Admin";
  // partnerName is the stable ledger identity behind the editable display
  // name — see AdminUser in schema.prisma.
  const seedPartnerName =
    PARTNERS.find((p) => p.toLowerCase() === seedAdminName.trim().toLowerCase()) ?? null;
  const admin = await prisma.adminUser.upsert({
    where: { email: seedAdminEmail },
    update: { name: seedAdminName, ...(seedPartnerName ? { partnerName: seedPartnerName } : {}) },
    create: {
      email: seedAdminEmail,
      passwordHash: await hashPassword(seedAdminPassword),
      name: seedAdminName,
      partnerName: seedPartnerName,
    },
  });
  if (seedAdminPassword === "change-me-immediately") {
    console.warn(
      `\n⚠️  Seeded admin "${seedAdminEmail}" with the default password "change-me-immediately".\n` +
        "   Log in and change it immediately, or set SEED_ADMIN_EMAIL / SEED_ADMIN_PASSWORD before seeding.\n",
    );
  }

  // ── Projects ───────────────────────────────────────────────────────
  type ProjectFixture = {
    slug: string;
    title: string;
    industry: string;
    service: string;
    description: string;
    tags: string[];
    photo: string;
    caseStudy: Record<string, unknown>;
  };
  const projects = loadFixture<ProjectFixture[]>("projects.json");

  // Matches the current homepage's hardcoded FEATURED_SLUGS in Portfolio.jsx
  // (see docs/CURRENT-SITE-INVENTORY.md) — replicated here as data instead
  // of code, per docs/DATA-MODEL.md §1's isFeatured/featuredOrder recommendation.
  const FEATURED_SLUGS = [
    "ai-customer-support-chatbot",
    "personalized-cold-email-outreach",
    "intelligent-content-repurposing-approval-workflow",
    "aurum-luxury-ecommerce-platform",
    "analytics-hub-saas-dashboard-platform",
  ];

  for (const p of projects) {
    const photoAsset = await upsertPlaceholderAsset(p.photo, p.title, admin.id);
    const featuredOrder = FEATURED_SLUGS.indexOf(p.slug);

    await prisma.project.upsert({
      where: { slug: p.slug },
      update: {
        title: p.title,
        industry: p.industry,
        service: p.service,
        description: p.description,
        tags: p.tags,
        photoId: photoAsset.id,
        caseStudy: p.caseStudy as never,
        isFeatured: featuredOrder >= 0,
        featuredOrder: featuredOrder >= 0 ? featuredOrder : null,
      },
      create: {
        slug: p.slug,
        title: p.title,
        industry: p.industry,
        service: p.service,
        description: p.description,
        tags: p.tags,
        photoId: photoAsset.id,
        caseStudy: p.caseStudy as never,
        isFeatured: featuredOrder >= 0,
        featuredOrder: featuredOrder >= 0 ? featuredOrder : null,
        createdBy: admin.id,
      },
    });
  }
  console.log(`  ${projects.length} projects seeded`);

  // ── Services ───────────────────────────────────────────────────────
  type SubServiceFixture = {
    id: string;
    icon: string;
    name: string;
    description: string;
    howWeWork: string[];
    whatYouGet: string[];
    platforms: string[];
  };
  type ServiceCategoryFixture = {
    id: string;
    serviceName: string;
    overviewIcon: string;
    gooeyId: string;
    overview: { heading: string; body: string };
    mobileSummary: unknown;
    subServices: SubServiceFixture[];
  };
  const categories = loadFixture<ServiceCategoryFixture[]>("services.json");

  for (const cat of categories) {
    const category = await prisma.serviceCategory.upsert({
      where: { slug: cat.id },
      update: {
        serviceName: cat.serviceName,
        overviewIcon: cat.overviewIcon,
        gooeyId: cat.gooeyId,
        overview: cat.overview as never,
        mobileSummary: cat.mobileSummary as never,
      },
      create: {
        slug: cat.id,
        serviceName: cat.serviceName,
        overviewIcon: cat.overviewIcon,
        gooeyId: cat.gooeyId,
        overview: cat.overview as never,
        mobileSummary: cat.mobileSummary as never,
      },
    });

    for (const [index, sub] of cat.subServices.entries()) {
      await prisma.subService.upsert({
        where: { categoryId_slug: { categoryId: category.id, slug: sub.id } },
        update: {
          icon: sub.icon,
          name: sub.name,
          description: sub.description,
          howWeWork: sub.howWeWork,
          whatYouGet: sub.whatYouGet,
          platforms: sub.platforms,
          order: index,
        },
        create: {
          categoryId: category.id,
          slug: sub.id,
          icon: sub.icon,
          name: sub.name,
          description: sub.description,
          howWeWork: sub.howWeWork,
          whatYouGet: sub.whatYouGet,
          platforms: sub.platforms,
          order: index,
        },
      });
    }
  }
  console.log(`  ${categories.length} service categories seeded`);

  // ── Reviews ────────────────────────────────────────────────────────
  type ReviewFixture = { id: string; name: string; location: string; service: string; text: string };
  const reviews = loadFixture<ReviewFixture[]>("reviews.json");

  for (const [index, r] of reviews.entries()) {
    await prisma.review.upsert({
      where: { displayId: r.id },
      update: { name: r.name, location: r.location, service: r.service, text: r.text, order: index },
      create: {
        displayId: r.id,
        name: r.name,
        location: r.location,
        service: r.service,
        text: r.text,
        order: index,
      },
    });
  }
  console.log(`  ${reviews.length} reviews seeded`);

  // ── Team ───────────────────────────────────────────────────────────
  type TeamFixture = { name: string; role: string; photo: string | null };
  const team = loadFixture<TeamFixture[]>("team.json");

  for (const [index, member] of team.entries()) {
    const photoAsset = member.photo
      ? await upsertPlaceholderAsset(member.photo, member.name, admin.id)
      : null;

    const existing = await prisma.teamMember.findFirst({ where: { name: member.name } });
    if (existing) {
      await prisma.teamMember.update({
        where: { id: existing.id },
        data: { role: member.role, photoId: photoAsset?.id ?? null, order: index },
      });
    } else {
      await prisma.teamMember.create({
        data: { name: member.name, role: member.role, photoId: photoAsset?.id ?? null, order: index },
      });
    }
  }
  console.log(`  ${team.length} team members seeded`);

  console.log("\nSeed complete.");
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
