import TacticalGlobe3D from "./vendor/TacticalGlobe3D.js";

// The component only exposes two fills: `landFill` (the default, used for
// any country that's either unlisted or explicitly `enabled: true`) and
// `disabledColor` (used only for countries listed here with `enabled:
// false`). There's no separate "highlight" color, so the served countries
// below stay dim; every OTHER country in the world-atlas dataset is listed
// explicitly as disabled so it renders in the muted base color instead —
// that's what makes the served countries read as "lit up" by contrast.
//
// Served countries (kept bright, left out of this list): United States,
// Canada, Dominican Republic, Ecuador, France, Argentina, New Zealand,
// Australia, India, Pakistan, Botswana, Oman, UAE, Saudi Arabia, Sweden,
// UK, Germany, Netherlands, Belgium, Spain, Portugal, Switzerland, Italy,
// Slovenia, Croatia, Serbia, Greece, Morocco, Algeria. (Puerto Rico isn't
// present as its own shape in this simplified world-atlas dataset.)
const DIMMED_COUNTRIES = [
  { code: "AFG", name: "Afghanistan", enabled: false },
  { code: "AGO", name: "Angola", enabled: false },
  { code: "ALB", name: "Albania", enabled: false },
  { code: "ARM", name: "Armenia", enabled: false },
  { code: "ATA", name: "Antarctica", enabled: false },
  { code: "AUT", name: "Austria", enabled: false },
  { code: "AZE", name: "Azerbaijan", enabled: false },
  { code: "BDI", name: "Burundi", enabled: false },
  { code: "BEN", name: "Benin", enabled: false },
  { code: "BFA", name: "Burkina Faso", enabled: false },
  { code: "BGD", name: "Bangladesh", enabled: false },
  { code: "BGR", name: "Bulgaria", enabled: false },
  { code: "BIH", name: "Bosnia and Herz.", enabled: false },
  { code: "BLR", name: "Belarus", enabled: false },
  { code: "BLZ", name: "Belize", enabled: false },
  { code: "BOL", name: "Bolivia", enabled: false },
  { code: "BRA", name: "Brazil", enabled: false },
  { code: "BRN", name: "Brunei", enabled: false },
  { code: "BTN", name: "Bhutan", enabled: false },
  { code: "CAF", name: "Central African Rep.", enabled: false },
  { code: "CHL", name: "Chile", enabled: false },
  { code: "CHN", name: "China", enabled: false },
  { code: "CIV", name: "C\xf4te d'Ivoire", enabled: false },
  { code: "CMR", name: "Cameroon", enabled: false },
  { code: "COD", name: "Dem. Rep. Congo", enabled: false },
  { code: "COG", name: "Congo", enabled: false },
  { code: "COL", name: "Colombia", enabled: false },
  { code: "COM", name: "Comoros", enabled: false },
  { code: "CRI", name: "Costa Rica", enabled: false },
  { code: "CUB", name: "Cuba", enabled: false },
  { code: "CYP", name: "Cyprus", enabled: false },
  { code: "CZE", name: "Czechia", enabled: false },
  { code: "DJI", name: "Djibouti", enabled: false },
  { code: "DNK", name: "Denmark", enabled: false },
  { code: "EGY", name: "Egypt", enabled: false },
  { code: "ERI", name: "Eritrea", enabled: false },
  { code: "EST", name: "Estonia", enabled: false },
  { code: "ETH", name: "Ethiopia", enabled: false },
  { code: "FIN", name: "Finland", enabled: false },
  { code: "FJI", name: "Fiji", enabled: false },
  { code: "GAB", name: "Gabon", enabled: false },
  { code: "GEO", name: "Georgia", enabled: false },
  { code: "GHA", name: "Ghana", enabled: false },
  { code: "GIN", name: "Guinea", enabled: false },
  { code: "GMB", name: "Gambia", enabled: false },
  { code: "GNB", name: "Guinea-Bissau", enabled: false },
  { code: "GNQ", name: "Eq. Guinea", enabled: false },
  { code: "GRL", name: "Greenland", enabled: false },
  { code: "GTM", name: "Guatemala", enabled: false },
  { code: "GUY", name: "Guyana", enabled: false },
  { code: "HND", name: "Honduras", enabled: false },
  { code: "HTI", name: "Haiti", enabled: false },
  { code: "HUN", name: "Hungary", enabled: false },
  { code: "IDN", name: "Indonesia", enabled: false },
  { code: "IRL", name: "Ireland", enabled: false },
  { code: "IRN", name: "Iran", enabled: false },
  { code: "IRQ", name: "Iraq", enabled: false },
  { code: "ISL", name: "Iceland", enabled: false },
  { code: "ISR", name: "Israel", enabled: false },
  { code: "JAM", name: "Jamaica", enabled: false },
  { code: "JOR", name: "Jordan", enabled: false },
  { code: "JPN", name: "Japan", enabled: false },
  { code: "KAZ", name: "Kazakhstan", enabled: false },
  { code: "KEN", name: "Kenya", enabled: false },
  { code: "KGZ", name: "Kyrgyzstan", enabled: false },
  { code: "KHM", name: "Cambodia", enabled: false },
  { code: "KOR", name: "South Korea", enabled: false },
  { code: "KWT", name: "Kuwait", enabled: false },
  { code: "LAO", name: "Laos", enabled: false },
  { code: "LBN", name: "Lebanon", enabled: false },
  { code: "LBR", name: "Liberia", enabled: false },
  { code: "LBY", name: "Libya", enabled: false },
  { code: "LKA", name: "Sri Lanka", enabled: false },
  { code: "LSO", name: "Lesotho", enabled: false },
  { code: "LTU", name: "Lithuania", enabled: false },
  { code: "LUX", name: "Luxembourg", enabled: false },
  { code: "LVA", name: "Latvia", enabled: false },
  { code: "MDA", name: "Moldova", enabled: false },
  { code: "MDG", name: "Madagascar", enabled: false },
  { code: "MEX", name: "Mexico", enabled: false },
  { code: "MKD", name: "North Macedonia", enabled: false },
  { code: "MLI", name: "Mali", enabled: false },
  { code: "MMR", name: "Myanmar", enabled: false },
  { code: "MNE", name: "Montenegro", enabled: false },
  { code: "MNG", name: "Mongolia", enabled: false },
  { code: "MOZ", name: "Mozambique", enabled: false },
  { code: "MRT", name: "Mauritania", enabled: false },
  { code: "MWI", name: "Malawi", enabled: false },
  { code: "MYS", name: "Malaysia", enabled: false },
  { code: "NAM", name: "Namibia", enabled: false },
  { code: "NCL", name: "New Caledonia", enabled: false },
  { code: "NER", name: "Niger", enabled: false },
  { code: "NGA", name: "Nigeria", enabled: false },
  { code: "NIC", name: "Nicaragua", enabled: false },
  { code: "NOR", name: "Norway", enabled: false },
  { code: "NPL", name: "Nepal", enabled: false },
  { code: "PAN", name: "Panama", enabled: false },
  { code: "PER", name: "Peru", enabled: false },
  { code: "PHL", name: "Philippines", enabled: false },
  { code: "PNG", name: "Papua New Guinea", enabled: false },
  { code: "POL", name: "Poland", enabled: false },
  { code: "PRK", name: "North Korea", enabled: false },
  { code: "PRY", name: "Paraguay", enabled: false },
  { code: "PSE", name: "Palestine", enabled: false },
  { code: "QAT", name: "Qatar", enabled: false },
  { code: "ROU", name: "Romania", enabled: false },
  { code: "RUS", name: "Russia", enabled: false },
  { code: "RWA", name: "Rwanda", enabled: false },
  { code: "SDN", name: "Sudan", enabled: false },
  { code: "SEN", name: "Senegal", enabled: false },
  { code: "SGP", name: "Singapore", enabled: false },
  { code: "SLB", name: "Solomon Islands", enabled: false },
  { code: "SLE", name: "Sierra Leone", enabled: false },
  { code: "SLV", name: "El Salvador", enabled: false },
  { code: "SOM", name: "Somalia", enabled: false },
  { code: "SSD", name: "South Sudan", enabled: false },
  { code: "SUR", name: "Suriname", enabled: false },
  { code: "SVK", name: "Slovakia", enabled: false },
  { code: "SWZ", name: "Eswatini", enabled: false },
  { code: "SYR", name: "Syria", enabled: false },
  { code: "TCD", name: "Chad", enabled: false },
  { code: "TGO", name: "Togo", enabled: false },
  { code: "THA", name: "Thailand", enabled: false },
  { code: "TJK", name: "Tajikistan", enabled: false },
  { code: "TKM", name: "Turkmenistan", enabled: false },
  { code: "TLS", name: "Timor-Leste", enabled: false },
  { code: "TTO", name: "Trinidad and Tobago", enabled: false },
  { code: "TUN", name: "Tunisia", enabled: false },
  { code: "TUR", name: "Turkey", enabled: false },
  { code: "TWN", name: "Taiwan", enabled: false },
  { code: "TZA", name: "Tanzania", enabled: false },
  { code: "UGA", name: "Uganda", enabled: false },
  { code: "UKR", name: "Ukraine", enabled: false },
  { code: "URY", name: "Uruguay", enabled: false },
  { code: "UZB", name: "Uzbekistan", enabled: false },
  { code: "VEN", name: "Venezuela", enabled: false },
  { code: "VNM", name: "Vietnam", enabled: false },
  { code: "VUT", name: "Vanuatu", enabled: false },
  { code: "XKX", name: "Kosovo", enabled: false },
  { code: "YEM", name: "Yemen", enabled: false },
  { code: "ZAF", name: "South Africa", enabled: false },
  { code: "ZMB", name: "Zambia", enabled: false },
  { code: "ZWE", name: "Zimbabwe", enabled: false },
];

// This vendored component (see vendor/TacticalGlobe3D.js) reads every one of
// these prop groups directly with no internal fallback, so unlike a normal
// Framer canvas render, which injects the property-panel defaults, we have
// to supply the full tree ourselves. Colors are tuned to the site's
// black/orange palette instead of the component's default blue/grey.
export function AboutGlobe() {
  return (
    <TacticalGlobe3D
      markers={[]}
      countries={DIMMED_COUNTRIES}
      mapStyle={{
        oceanColor: "#0d0704",
        landFill: "#ff8c3a",
        landStroke: "#5a3a1e",
        strokeWidth: 0.5,
        hoverColor: "#ffb066",
        disabledColor: "#241608",
      }}
      tooltip={{
        show: true,
        background: "rgba(21, 12, 5, 0.92)",
        textColor: "#ffffff",
        borderColor: "rgba(255, 178, 71, 0.35)",
      }}
      grid={{ show: true, color: "#7a5230", opacity: 0.2 }}
      layout={{ cornerRadius: 0, padding: 8, showBorder: false, borderColor: "rgba(255,255,255,0.1)" }}
      interaction={{
        autoRotate: true,
        autoRotateSpeed: 6,
        rotateX: 0,
        rotateY: -15,
        rotateZ: -20,
        enableDrag: true,
        dragSensitivity: 0.4,
        glowColor: "#ff7a1a",
        // 0 = no atmosphere halo ring around the sphere, so the globe sits
        // directly on the page background with no glow of its own.
        glowIntensity: 0,
        showStars: true,
        showLabels: true,
      }}
    />
  );
}
